#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LeafChecker.Resource", IsApplication=true)]

namespace LeafChecker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int theme_black_notitlebar_fullscreen_background = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Brzoza = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Buk = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Dab = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Jarzab = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Kasztanowiec = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Klon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Lipa = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Los = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int trees = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int trees2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int trees2mobile = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Wierzba = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int appDescription = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int appName = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int findAnother = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int getIn = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int isLimes = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int leafImg = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int madePhotoBtn = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int manual = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int noLimes = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int percent = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int photoView = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int stupid = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LeafMainLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LeafRecognition = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NotRecognizeView = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int appDescription = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int appName = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int isLimes = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int loadImage = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int lookTrees = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int manual = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int noLimes = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int openCamera = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int percent = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int stupid = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
